name: CI
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: action/setup-node@v3
        with:
          node-version: 20.13.1
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint && pnpm run build
